# 08 - Druggability of the alveolar-macrophage hyperoxia response.
#
# Ported from code/drug_target_figures.R (Route A, lines 36-133).
#
# Inputs  Table S3 (from 04), frozen Open Targets annotation
# Outputs Fig 6A    druggability-annotated volcano, alveolar macrophages
#         Fig 6B    druggable targets ranked by effect size
#         Fig 6C    Lgals3 across CD45+ cell types
#         Fig 6D    baseline-expression ECDF with Lgals3 highlighted
#         Table S5  all 257 human orthologs of the AM-upregulated genes,
#                   annotated where Open Targets had a record and explicitly
#                   marked where it did not
#
# FROZEN INPUT ---------------------------------------------------------------
# data/frozen/drug_target_annotation_2026-06-30.csv is NOT regenerated by this
# pipeline. It was produced by a query against the Open Targets Platform
# GraphQL API v4 on 30 June 2026; the API responses were not retained and the
# schema has since changed, so the query cannot be replayed. The file is
# therefore version-controlled as a frozen input, exactly as deposited
# alongside the manuscript (Supplemental Table S5).
#
# scripts/aux_opentargets_requery.R queries the current schema and caches its
# responses. It yields a different target list (202 rows, different tier
# vocabulary) and so does NOT reproduce the published figures; it sits outside
# the numbered pipeline and is retained only as a path to re-deriving the
# annotation in future work.

source(file.path("config", "paths.R"))
source(file.path("R", "figure_io.R"))
source(file.path("R", "plots.R"))
suppressMessages({
  library(Seurat)
  library(readxl)
  library(ggplot2)
  library(ggrepel)
  library(DESeq2)
  library(babelgene)
})

annotation_file <- file.path(data_dir, "frozen",
                             "drug_target_annotation_2026-06-30.csv")
if (!file.exists(annotation_file)) {
  stop("Frozen Open Targets annotation not found: ", annotation_file)
}
drug <- read.csv(annotation_file, stringsAsFactors = FALSE)
expect_value("frozen druggability annotation rows", nrow(drug), 138)

# ---- alveolar macrophage DE table ------------------------------------------
am <- as.data.frame(read_excel(deseq_xlsx, sheet = "Alveolar macrophages"))
am <- am[!is.na(am$padj), ]
am$pvalue[am$pvalue < 1e-50] <- 1e-50

up_mouse <- am$gene[am$padj < padj_de & am$log2FoldChange > 0]
expect_value("alveolar macrophage genes upregulated", length(up_mouse), 262)

# ---- Table S5: the full 262 -> 257 -> annotated funnel ----------------------
# The frozen annotation holds only genes for which Open Targets returned a
# record, and spans every cell type. Table S4 is rebuilt here as one row per
# human ortholog of the AM-upregulated genes, so that each step of the funnel
# quoted in the Results can be checked directly in the table. Orthologs with
# no Open Targets record are retained and marked rather than dropped.
orth <- orthologs(genes = up_mouse, species = "mouse", human = FALSE)
map <- data.frame(
  mouse_gene = orth$symbol, human_symbol = orth$human_symbol,
  stringsAsFactors = FALSE
)
map <- map[!is.na(map$human_symbol) & map$human_symbol != "", ]
map <- aggregate(mouse_gene ~ human_symbol, data = map,
                 FUN = function(x) paste(sort(unique(x)), collapse = "/"))

# babelgene ships its own ortholog tables, so a package update can change this
# count; warn rather than stop, since only the row count would shift.
expect_value("human orthologs mapped", nrow(map), 257, on_fail = "warn")

s4 <- merge(map, drug, by = "human_symbol", all.x = TRUE,
            suffixes = c("", "_annotation"))
s4$annotated <- !is.na(s4$tier)
s4$tier[is.na(s4$tier)] <- "Not annotated"
s4$druggable_any[is.na(s4$druggable_any)] <- FALSE
s4$am_log2FC <- am$log2FoldChange[match(s4$human_symbol, toupper(am$gene))]
s4 <- s4[order(!s4$annotated, s4$tier, -rank(s4$am_log2FC, na.last = "keep")), ]

n_annotated <- sum(s4$annotated)
n_drugged <- sum(s4$tier == "A: existing drug")
expect_value("orthologs with a druggability annotation", n_annotated, 92)
expect_value("orthologs with an approved/clinical-stage drug", n_drugged, 11)
message(sprintf("  funnel: %d AM-up genes -> %d orthologs -> %d annotated -> %d drugged",
                length(up_mouse), nrow(map), n_annotated, n_drugged))

save_table("TableS5_drug_targets", s4, path = drug_csv)

druggable_mouse <- unique(unlist(strsplit(drug$mouse_genes, "/")))
hasdrug_mouse <- unique(unlist(strsplit(
  drug$mouse_genes[drug$tier == "A: existing drug"], "/"
)))

am$drugclass <- ifelse(am$gene %in% hasdrug_mouse, "Druggable (existing drug)",
  ifelse(am$gene %in% druggable_mouse, "Druggable", "Not druggable")
)
am$drugclass <- factor(am$drugclass,
  levels = c("Not druggable", "Druggable", "Druggable (existing drug)")
)

# ---- Fig 6A: druggability-annotated volcano --------------------------------
lab <- am[am$drugclass != "Not druggable" &
  am$log2FoldChange > 0.5 & am$pvalue < 1e-5, ]
lab <- lab[order(-lab$log2FoldChange), ]

p6a <- ggplot(am[am$log2FoldChange > 0, ], aes(
  .data$log2FoldChange, -log10(.data$pvalue), color = .data$drugclass
)) +
  geom_point(alpha = 0.6, size = 1.4) +
  ggrepel::geom_text_repel(
    data = lab, aes(label = .data$gene), color = "black",
    size = 3, max.overlaps = 20, min.segment.length = 0
  ) +
  scale_color_manual(
    values = c(
      "Not druggable" = "grey80", "Druggable" = "#4393c3",
      "Druggable (existing drug)" = "#d6604d"
    ), name = NULL
  ) +
  labs(
    x = "log2 fold change [O2/Air]", y = "-log10 p-value",
    title = "Alveolar macrophages: druggable upregulated targets"
  ) +
  theme_classic() +
  theme(legend.position = "top")
save_panel("Fig6A", p6a,
  data = am[am$log2FoldChange > 0,
            c("gene", "log2FoldChange", "pvalue", "padj", "drugclass")],
  width = 6, height = 6, slug = "druggable_volcano"
)

# ---- Fig 6B: druggable targets ranked by effect size -----------------------
# Ranked on the alveolar-macrophage fold change from Table S2, not on the
# cross-cell-type max_log2FC stored in the annotation.
cand <- drug[grepl("Alveolar macrophages", drug$celltypes, ignore.case = TRUE) &
  drug$tier %in% c("A: existing drug", "B: clinically tractable"), ]
cand$am_fc <- am$log2FoldChange[match(cand$mouse_genes, am$gene)]
cand$am_pval <- am$pvalue[match(cand$mouse_genes, am$gene)]
cand <- cand[order(-cand$am_fc), ]
cand$label_drug <- sub(";.*$", "", cand$example_drugs)
cand$human_symbol <- factor(cand$human_symbol, levels = rev(cand$human_symbol))

expect_value("targets plotted in Fig 6B", nrow(cand), 11)
expect_value("highest-ranked Fig 6B targets",
             as.character(utils::head(cand$human_symbol, 3)),
             c("SPP1", "GPNMB", "TXNRD1"))

p6b <- ggplot(cand, aes(.data$am_fc, .data$human_symbol, color = .data$tier)) +
  geom_segment(
    aes(x = 0, xend = .data$am_fc, yend = .data$human_symbol),
    color = "grey70", linewidth = 0.5
  ) +
  geom_point(aes(size = -log10(.data$am_pval))) +
  geom_text(aes(label = .data$label_drug),
    hjust = -0.1, vjust = 0.5, size = 3, color = "grey25"
  ) +
  scale_color_manual(
    values = c("A: existing drug" = "#d6604d",
               "B: clinically tractable" = "#4393c3"), name = NULL
  ) +
  xlim(0, max(cand$am_fc) * 1.45) +
  labs(
    x = "log2 fold change (O2/Air)", y = NULL,
    title = "Druggable upregulated targets (Alveolar macrophages)"
  ) +
  theme_classic() +
  theme(legend.position = "top")
save_panel("Fig6B", p6b,
  data = cand[, c("human_symbol", "mouse_genes", "tier", "am_fc", "am_pval",
                  "example_drugs")],
  width = 6.5, height = 6, slug = "ranked_targets"
)

# ---- Fig 6C: Lgals3 specificity across the CD45+ atlas ---------------------
# In the working script this was the right-hand half of a two-panel composite
# (A3_galectin3_spotlight.pdf); it is a panel in its own right in the paper.
seu <- load_annotated()
p6c <- VlnPlot(seu, features = "Lgals3", group.by = "celltype", pt.size = 0) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(title = "Lgals3 across cell types", x = NULL)

lgals3 <- GetAssayData(seu, assay = "SCT", layer = "data")["Lgals3", ]
save_panel("Fig6C", p6c,
  data = data.frame(
    cell_type = names(tapply(lgals3, seu@meta.data$celltype, mean)),
    mean_lognorm = as.numeric(tapply(lgals3, seu@meta.data$celltype, mean)),
    pct_detected = as.numeric(tapply(lgals3, seu@meta.data$celltype,
                                     function(v) mean(v > 0)))
  ),
  width = 7, height = 4, slug = "lgals3_violin"
)

# ---- Fig 6D: baseline-expression ECDF --------------------------------------
am$rank <- rank(am$baseMean)
highlight <- c("Lgals3", "Spp1", "Gpnmb", "Txnrd1")
p6d <- ggplot(am, aes(log(.data$baseMean))) +
  labs(x = "Baseline expression [log]", y = "Percentile") +
  stat_ecdf() +
  ggrepel::geom_text_repel(
    data = am[am$gene %in% highlight, ],
    aes(x = log(.data$baseMean), y = .data$rank / nrow(am),
        label = .data$gene)
  ) +
  theme_classic()
save_panel("Fig6D", p6d,
  data = am[am$gene %in% highlight,
            c("gene", "baseMean", "rank", "log2FoldChange", "padj")],
  width = 4, height = 4, slug = "lgals3_ecdf"
)

lgals3_pct <- am$rank[am$gene == "Lgals3"] / nrow(am)
message(sprintf("  Lgals3 baseline-expression percentile: %.1f%%",
                100 * lgals3_pct))

message("08_drug_targets.R complete")
